# Compare Lexicons

We compare the streams generated with 

1. controlled lexicons (ours),
2. random baseline streams, and
3. streams generated based on reference lexicons from the literature

based on the repetitiveness of the phoneme features.

### Collect Results

We collect all stream generation results and their feature repetitiveness scores in a dataframe. To generate the data, you must run 
```bash
./generate_all_datasets.sh
```

In [2]:
import glob
import pandas as pd
from alparc import load_streams

all_streams = [
    ("ALPARC-DEU", load_streams(glob.glob("results/default_german_*")[-1] + "/_arpac/streams.json")), 
    ("ALPARC-DEU-3w", load_streams(glob.glob("results/default_3words_no_rnd_*")[-1] + "/_arpac/streams.json")),
    ("ALPARC-DEU-5w", load_streams(glob.glob("results/default_5words_no_rnd_*")[-1] + "/_arpac/streams.json")), 
    ("ALPARC-DEU-2s", load_streams(glob.glob("results/default_2syllables_no_rnd_*")[-1] + "/_arpac/streams.json")),
    ("ALPARC-DEU-4s", load_streams(glob.glob("results/default_4syllables_no_rnd_*")[-1] + "/_arpac/streams.json")),
    ("ALPARC-ENG", load_streams(glob.glob("results/default_english_*")[-1] + "/_arpac/streams.json")), 
    ("ALPARC-RND", load_streams(glob.glob("results/random_german_*")[-1] + "/_arpac/streams.json")),
    ("ALPARC-RND", load_streams(glob.glob("results/random_english_*")[-1] + "/_arpac/streams.json")),
    ("BENCHMARK", load_streams(glob.glob("results/literature_streams_*")[-1] + "/_arpac/streams.json")), 
]

In [3]:
data = {"Control": [], "Lexicon": [], "Cumulative feature overlap": [], "Feature": [], "PRI": [], "Stream TP mode": [], "Stream": []}

mode_to_mode = {  # TP-uniform position-random; TP-uniform position-fixed and TP-structured
    "random": "TP-uniform position-random",
    "word_structured": "TP-structured",
    "position_controlled": "TP-uniform position-fixed"
}

for control, streams in all_streams:
    for stream in streams:
        for k, v in stream.info["rhythmicity_indexes"].items():
            data["Feature"].append(k)
            data["PRI"].append(v)
            data["Control"].append(control)
            data["Lexicon"].append(str(stream.info["lexicon"]))
            data["Stream TP mode"].append(mode_to_mode[stream.info["stream_tp_mode"]])
            data["Stream"].append("|".join(syll.id for syll in stream))
            data["Cumulative feature overlap"].append(stream.info["lexicon_info"]["cumulative_feature_repetitiveness"])
        data["Feature"].append("max")
        data["PRI"].append(max(stream.info["rhythmicity_indexes"].values()))
        data["Control"].append(control)
        data["Lexicon"].append(str(stream.info["lexicon"]))
        data["Stream TP mode"].append(mode_to_mode[stream.info["stream_tp_mode"]])
        data["Stream"].append("|".join(syll.id for syll in stream))
        data["Cumulative feature overlap"].append(stream.info["lexicon_info"]["cumulative_feature_repetitiveness"])

df = pd.DataFrame(data)

df.Control = df.Control.astype("category")
df.Control = df.Control.cat.set_categories([
    "ALPARC-DEU", 
    "ALPARC-DEU-3w",
    "ALPARC-DEU-5w", 
    "ALPARC-DEU-2s",
    "ALPARC-DEU-4s",
    "ALPARC-ENG", 
    "ALPARC-RND",
    "BENCHMARK",
])

df = df.sort_values(["Control", "Lexicon", "Stream TP mode"]).reset_index(drop=True)

import os
os.makedirs("results/", exist_ok=True)
df.to_csv("results/analysis_full_dataset.csv")

df

,Control,Lexicon,Cumulative feature overlap,Feature,PRI,Stream TP mode,Stream
0,ALPARC-DEU,biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː,2,phon_1_son,0.093838,TP-structured,ʃuː|kaː|myː|biː|huː|ʃøː|ɡɛː|fiː|lyː|høː|ʃiː|pa...
1,ALPARC-DEU,biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː,2,phon_1_back,0.000000,TP-structured,ʃuː|kaː|myː|biː|huː|ʃøː|ɡɛː|fiː|lyː|høː|ʃiː|pa...
2,ALPARC-DEU,biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː,2,phon_1_hi,0.000000,TP-structured,ʃuː|kaː|myː|biː|huː|ʃøː|ɡɛː|fiː|lyː|høː|ʃiː|pa...
3,ALPARC-DEU,biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː,2,phon_1_lab,0.098039,TP-structured,ʃuː|kaː|myː|biː|huː|ʃøː|ɡɛː|fiː|lyː|høː|ʃiː|pa...
4,ALPARC-DEU,biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː,2,phon_1_cor,0.096639,TP-structured,ʃuː|kaː|myː|biː|huː|ʃøː|ɡɛː|fiː|lyː|høː|ʃiː|pa...
...,...,...,...,...,...,...,...
71484,BENCHMARK,ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku,4,phon_1_voi,0.040616,TP-uniform position-random,da|pi|doʊ|ti|bi|la|tu|bu|ku|ɹoʊ|ɡoʊ|pa|pi|ti|d...
71485,BENCHMARK,ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku,4,phon_2_back,0.014006,TP-uniform position-random,da|pi|doʊ|ti|bi|la|tu|bu|ku|ɹoʊ|ɡoʊ|pa|pi|ti|d...
71486,BENCHMARK,ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku,4,phon_2_hi,0.015406,TP-uniform position-random,da|pi|doʊ|ti|bi|la|tu|bu|ku|ɹoʊ|ɡoʊ|pa|pi|ti|d...
71487,BENCHMARK,ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku,4,phon_2_lo,0.037815,TP-uniform position-random,da|pi|doʊ|ti|bi|la|tu|bu|ku|ɹoʊ|ɡoʊ|pa|pi|ti|d...
71488,BENCHMARK,ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku,4,max,0.092437,TP-uniform position-random,da|pi|doʊ|ti|bi|la|tu|bu|ku|ɹoʊ|ɡoʊ|pa|pi|ti|d...

In [4]:
df_lexicons = df[["Control", "Lexicon"]].drop_duplicates().reset_index(drop=True)
df_lexicons.to_csv("results/analysis_all_lexicons.csv")
df_lexicons

        Control                                  Lexicon
0    ALPARC-DEU  biːhuːʃøː|ɡɛːfiːlyː|ʃuːkaːmyː|høːʃiːpaː
1    ALPARC-DEU  biːseːhøː|laːfoːɡiː|suːhiːpaː|kɛːfyːroː
2    ALPARC-DEU  buːheːʃiː|nyːkuːvaː|zɛːbeːhøː|çaːloːpuː
3    ALPARC-DEU  heːboːsiː|baːhoːzɛː|suːkaːmɛː|høːʃiːpaː
4    ALPARC-DEU  heːboːsiː|nyːkuːvaː|zɛːbeːhøː|faːnøːɡɛː
..          ...                                      ...
172   BENCHMARK              pukemi|rafinu|binapo|medoxi
173   BENCHMARK              tifaxu|soduxi|melubo|ɡanipe
174   BENCHMARK           tupiɹoʊ|ɡoʊlabu|padoʊti|bidaku
175   BENCHMARK              ɡonabe|mudila|ronixe|pikusa
176   BENCHMARK           ɡoʊlatu|daɹoʊpi|tibudoʊ|pabiku

[177 rows x 2 columns]

In [5]:
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
from pingouin import ttest
import itertools

tp_modes = ["TP-uniform position-random", "TP-uniform position-fixed", "TP-structured"]
dfs = []

for i, tp_mode in enumerate(tp_modes):
    for one, two in itertools.combinations([
    "ALPARC-DEU",
    "ALPARC-ENG", 
    "ALPARC-RND",
    "BENCHMARK"], 2):
        df2 = df[(df["Stream TP mode"] == tp_mode) & (df["Feature"] == "max")]
        cat1 = df2[df2['Control'] == one]["PRI"]
        cat2 = df2[df2['Control'] == two]["PRI"]
        print(tp_mode, one, two)
        this = ttest(list(cat1), list(cat2), alternative="two-sided")
        this.index = pd.MultiIndex.from_tuples([(tp_mode, f"{one} vs. {two}")], names=["Stream TP mode", "Controls"])
        dfs.append(this)

ttest_df = pd.concat(dfs).rename({"dof": "df"}, axis=1)

display(ttest_df)

ttest_df.to_csv("results/table_1.csv", index=True)

TP-uniform position-random ALPARC-DEU ALPARC-ENG
TP-uniform position-random ALPARC-DEU ALPARC-RND
TP-uniform position-random ALPARC-DEU BENCHMARK
TP-uniform position-random ALPARC-ENG ALPARC-RND
TP-uniform position-random ALPARC-ENG BENCHMARK
TP-uniform position-random ALPARC-RND BENCHMARK
TP-uniform position-fixed ALPARC-DEU ALPARC-ENG
TP-uniform position-fixed ALPARC-DEU ALPARC-RND
TP-uniform position-fixed ALPARC-DEU BENCHMARK
TP-uniform position-fixed ALPARC-ENG ALPARC-RND
TP-uniform position-fixed ALPARC-ENG BENCHMARK
TP-uniform position-fixed ALPARC-RND BENCHMARK
TP-structured ALPARC-DEU ALPARC-ENG
TP-structured ALPARC-DEU ALPARC-RND
TP-structured ALPARC-DEU BENCHMARK
TP-structured ALPARC-ENG ALPARC-RND
TP-structured ALPARC-ENG BENCHMARK
TP-structured ALPARC-RND BENCHMARK

                                                              T          df  \
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG   0.462262  418.000000
                           ALPARC-DEU vs. ALPARC-RND   0.807031  391.744779
                           ALPARC-DEU vs. BENCHMARK    7.343796  418.000000
                           ALPARC-ENG vs. ALPARC-RND   0.286214  411.598128
                           ALPARC-ENG vs. BENCHMARK    7.083895  418.000000
                           ALPARC-RND vs. BENCHMARK    7.946259  413.040662
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG  -0.246602  418.000000
                           ALPARC-DEU vs. ALPARC-RND -21.939723  430.087749
                           ALPARC-DEU vs. BENCHMARK  -16.670947  418.000000
                           ALPARC-ENG vs. ALPARC-RND -21.843037  434.153229
                           ALPARC-ENG vs. BENCHMARK  -16.414966  418.000000
                           ALPARC-RND vs. BENCHMARK   12.532642  572.368582
TP-structured              ALPARC-DEU vs. ALPARC-ENG  -6.707053  333.681621
                           ALPARC-DEU vs. ALPARC-RND -27.215916  400.486450
                           ALPARC-DEU vs. BENCHMARK  -11.044540  201.389049
                           ALPARC-ENG vs. ALPARC-RND -26.798055  398.992416
                           ALPARC-ENG vs. BENCHMARK  -10.450553  199.952655
                           ALPARC-RND vs. BENCHMARK   15.616697  596.768356

                                                     alternative  \
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG   two-sided
                           ALPARC-DEU vs. ALPARC-RND   two-sided
                           ALPARC-DEU vs. BENCHMARK    two-sided
                           ALPARC-ENG vs. ALPARC-RND   two-sided
                           ALPARC-ENG vs. BENCHMARK    two-sided
                           ALPARC-RND vs. BENCHMARK    two-sided
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG   two-sided
                           ALPARC-DEU vs. ALPARC-RND   two-sided
                           ALPARC-DEU vs. BENCHMARK    two-sided
                           ALPARC-ENG vs. ALPARC-RND   two-sided
                           ALPARC-ENG vs. BENCHMARK    two-sided
                           ALPARC-RND vs. BENCHMARK    two-sided
TP-structured              ALPARC-DEU vs. ALPARC-ENG   two-sided
                           ALPARC-DEU vs. ALPARC-RND   two-sided
                           ALPARC-DEU vs. BENCHMARK    two-sided
                           ALPARC-ENG vs. ALPARC-RND   two-sided
                           ALPARC-ENG vs. BENCHMARK    two-sided
                           ALPARC-RND vs. BENCHMARK    two-sided

                                                             p-val  \
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG  6.441338e-01
                           ALPARC-DEU vs. ALPARC-RND  4.201381e-01
                           ALPARC-DEU vs. BENCHMARK   1.095479e-12
                           ALPARC-ENG vs. ALPARC-RND  7.748585e-01
                           ALPARC-ENG vs. BENCHMARK   5.984845e-12
                           ALPARC-RND vs. BENCHMARK   1.847692e-14
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG  8.053371e-01
                           ALPARC-DEU vs. ALPARC-RND  3.816383e-72
                           ALPARC-DEU vs. BENCHMARK   3.309434e-48
                           ALPARC-ENG vs. ALPARC-RND  6.649336e-72
                           ALPARC-ENG vs. BENCHMARK   4.317026e-47
                           ALPARC-RND vs. BENCHMARK   5.190788e-32
TP-structured              ALPARC-DEU vs. ALPARC-ENG  8.507878e-11
                           ALPARC-DEU vs. ALPARC-RND  4.254214e-93
                           ALPARC-DEU vs. BENCHMARK   1.771251e-22
                           ALPARC-ENG vs. ALPARC-RND  3.119797e-91
                           ALPARC-ENG vs. BENCHMARK   1.124508e-20
                           ALPARC-RND vs. BENCHMARK   2.390573e-46

                                                               CI95%  \
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG     [-0.0, 0.0]
                           ALPARC-DEU vs. ALPARC-RND     [-0.0, 0.0]
                           ALPARC-DEU vs. BENCHMARK     [0.01, 0.01]
                           ALPARC-ENG vs. ALPARC-RND     [-0.0, 0.0]
                           ALPARC-ENG vs. BENCHMARK     [0.01, 0.01]
                           ALPARC-RND vs. BENCHMARK     [0.01, 0.01]
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG    [-0.01, 0.0]
                           ALPARC-DEU vs. ALPARC-RND  [-0.34, -0.28]
                           ALPARC-DEU vs. BENCHMARK    [-0.13, -0.1]
                           ALPARC-ENG vs. ALPARC-RND  [-0.34, -0.28]
                           ALPARC-ENG vs. BENCHMARK    [-0.13, -0.1]
                           ALPARC-RND vs. BENCHMARK     [0.17, 0.23]
TP-structured              ALPARC-DEU vs. ALPARC-ENG   [-0.01, -0.0]
                           ALPARC-DEU vs. ALPARC-RND  [-0.38, -0.33]
                           ALPARC-DEU vs. BENCHMARK   [-0.12, -0.09]
                           ALPARC-ENG vs. ALPARC-RND  [-0.38, -0.32]
                           ALPARC-ENG vs. BENCHMARK   [-0.12, -0.08]
                           ALPARC-RND vs. BENCHMARK     [0.22, 0.28]

                                                       cohen-d        BF10  \
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG  0.045112        0.12
                           ALPARC-DEU vs. ALPARC-RND  0.069912       0.129
                           ALPARC-DEU vs. BENCHMARK   0.716681   6.028e+09
                           ALPARC-ENG vs. ALPARC-RND  0.024333       0.098
                           ALPARC-ENG vs. BENCHMARK   0.691317   1.174e+09
                           ALPARC-RND vs. BENCHMARK   0.674668   6.149e+11
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG  0.024066       0.111
                           ALPARC-DEU vs. ALPARC-RND  1.317144    6.33e+75
                           ALPARC-DEU vs. BENCHMARK   1.626918   4.231e+44
                           ALPARC-ENG vs. ALPARC-RND  1.313724   1.917e+75
                           ALPARC-ENG vs. BENCHMARK   1.601937    3.34e+43
                           ALPARC-RND vs. BENCHMARK   0.807093   9.157e+28
TP-structured              ALPARC-DEU vs. ALPARC-ENG  0.673444   1.139e+08
                           ALPARC-DEU vs. ALPARC-RND  1.667881  3.658e+102
                           ALPARC-DEU vs. BENCHMARK   1.101741   4.671e+21
                           ALPARC-ENG vs. ALPARC-RND  1.647979  4.328e+100
                           ALPARC-ENG vs. BENCHMARK   1.048949   3.813e+19
                           ALPARC-RND vs. BENCHMARK   1.110660   6.372e+42

                                                         power
Stream TP mode             Controls
TP-uniform position-random ALPARC-DEU vs. ALPARC-ENG  0.074703
                           ALPARC-DEU vs. ALPARC-RND  0.131062
                           ALPARC-DEU vs. BENCHMARK   1.000000
                           ALPARC-ENG vs. ALPARC-RND  0.059520
                           ALPARC-ENG vs. BENCHMARK   1.000000
                           ALPARC-RND vs. BENCHMARK   1.000000
TP-uniform position-fixed  ALPARC-DEU vs. ALPARC-ENG  0.056963
                           ALPARC-DEU vs. ALPARC-RND  1.000000
                           ALPARC-DEU vs. BENCHMARK   1.000000
                           ALPARC-ENG vs. ALPARC-RND  1.000000
                           ALPARC-ENG vs. BENCHMARK   1.000000
                           ALPARC-RND vs. BENCHMARK   1.000000
TP-structured              ALPARC-DEU vs. ALPARC-ENG  0.999999
                           ALPARC-DEU vs. ALPARC-RND  1.000000
                           ALPARC-DEU vs. BENCHMARK   1.000000
                           ALPARC-ENG vs. ALPARC-RND  1.000000
                           ALPARC-ENG vs. BENCHMARK   1.000000
                           ALPARC-RND vs. BENCHMARK   1.000000